# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'loginKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for loginKit

  # Pods for Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  # Pod for GoogleSignIn
  pod 'GoogleSignIn'

  # Pod for FBSignIn
  pod 'FBSDKLoginKit'
  pod ‘FacebookCore’
  pod ‘FacebookLogin’
	

  target 'loginKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'loginKitUITests' do
    # Pods for testing
  end

end
